#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import json
import sys
# agent is a NethServer library which provides function to communicate with the agent
import agent
import secrets
import stat

# Make the file executable by everyone
os.chmod(__file__, stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
data = json.load(sys.stdin)

# Setup default values
random_key = secrets.token_hex(16)
AUTHENTIK_SECRET_KEY = data.get("AUTHENTIK_SECRET_KEY",random_key)
AUTHENTIK_ERROR_REPORTING__ENABLED = True
# Talk with agent using file descriptor.

agent.set_env("AUTHENTIK_SECRET_KEY", AUTHENTIK_SECRET_KEY)

# Enable disable reporting for errors.

agent.set_env("AUTHENTIK_ERROR_REPORTING__ENABLED", AUTHENTIK_ERROR_REPORTING__ENABLED)

# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()